name = "accio"
description = "A spell-bound theme for zola"
license = "MIT"
homepage = ""
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Rajiv and Chirag"
homepage = ""

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
homepage = "https://accio-theme.netlify.app"
repo = "https://www.github.com/rajivharlalka/accio"